export const UsersData = [
  { id: 1, name: "Jasmin Tumulak",   email: "jasmine@utas.edu.om", password: "12345" },
  { id: 2, name: "Marian Malig-on",  email: "marian@utas.edu.om",  password: "12345" },
  { id: 3, name: "Ahmed Ali Jaboob", email: "ahmed@utas.edu.om",   password: "12345" },
  { id: 4, name: "Sara Al Balushi",  email: "sara@utas.edu.om",    password: "12345" },
  { id: 5, name: "Omar Al Farsi",    email: "omar@utas.edu.om",    password: "12345" },
];

export const RecipesData = [
  {
    title: "Chicken Biryani",
    ingredients: "Chicken, Basmati Rice, Onion, Tomato, Spices, Yogurt, Oil",
    instructions: "Marinate chicken, fry onions, layer rice and chicken, cook on low heat for 30 minutes.",
    email: "jasmine@utas.edu.om",
    category: "Lunch",
    difficulty: "Medium",
    isVegetarian: false,
    lastCooked: new Date("2024-10-15"),
    cookingTime: 45,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Biryani_at_Hyderabad%2C_India.jpg",
  },
  {
    title: "Vegetable Pasta",
    ingredients: "Pasta, Tomato Sauce, Bell Pepper, Mushroom, Garlic, Olive Oil, Cheese",
    instructions: "Boil pasta, saute vegetables, mix with sauce, top with cheese and serve.",
    email: "marian@utas.edu.om",
    category: "Dinner",
    difficulty: "Easy",
    isVegetarian: true,
    lastCooked: new Date("2024-11-01"),
    cookingTime: 20,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_vongole.jpg/1280px-Spaghetti_vongole.jpg",
  },
  {
    title: "Omani Shuwa",
    ingredients: "Lamb, Shuwa Spices, Banana Leaves, Garlic, Lemon",
    instructions: "Marinate lamb with spices overnight, wrap in banana leaves, slow cook underground for 24 hours.",
    email: "ahmed@utas.edu.om",
    category: "Dinner",
    difficulty: "Hard",
    isVegetarian: false,
    lastCooked: new Date("2024-09-20"),
    cookingTime: 90,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Shuwa.jpg/1280px-Shuwa.jpg",
  },
  {
    title: "Chocolate Brownies",
    ingredients: "Flour, Cocoa Powder, Sugar, Butter, Eggs, Vanilla, Chocolate Chips",
    instructions: "Mix dry ingredients, melt butter with chocolate, combine all, bake at 180C for 25 minutes.",
    email: "sara@utas.edu.om",
    category: "Dessert",
    difficulty: "Easy",
    isVegetarian: true,
    lastCooked: new Date("2024-11-10"),
    cookingTime: 25,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Chocolate_brownies.jpg/1280px-Chocolate_brownies.jpg",
  },
  {
    title: "Avocado Toast",
    ingredients: "Bread, Avocado, Lemon, Salt, Pepper, Chili Flakes, Egg",
    instructions: "Toast bread, mash avocado with lemon and salt, spread on toast, top with fried egg.",
    email: "omar@utas.edu.om",
    category: "Breakfast",
    difficulty: "Easy",
    isVegetarian: true,
    lastCooked: new Date("2024-11-12"),
    cookingTime: 20,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/2023_Avocado_Toast.jpg/1280px-2023_Avocado_Toast.jpg",
  },
];